name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip and check
        run: |
          unzip BlogApp.zip
          echo "=== Folder awm zawng zawng ==="
          ls -la
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Make gradlew executable
        run: chmod +x */gradlew gradlew || true
      - name: Build APK
        run: ./*/gradlew assembleDebug || ./gradlew assembleDebug
      - name: Find APK location
        run: find . -name "*.apk"
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: '**/*.apk'
