name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip BlogApp
        run: unzip BlogApp.zip
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          
      - name: Build Debug APK
        run: |
          cd BlogApp
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: 'BlogApp/app/build/outputs/apk/debug/*.apk'
          if-no-files-found: error
